<?php

namespace App\Services;

use App\Models\Beneficiary;
use App\Models\CashGrantDistribution;
use App\Models\DuplicateDetectionLog;
use App\Models\QrCode;
use App\Models\VerificationActivityLog;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class DataExportService
{
    // ─────────────────────────────────────────────────────────────
    // exportToPDF
    // ─────────────────────────────────────────────────────────────

    public function exportToPDF(array $data, string $reportType, array $filters, string $filename): \Symfony\Component\HttpFoundation\Response
    {
        $viewMap = [
            'beneficiary'  => 'reports.beneficiary_statistics',
            'compliance'   => 'reports.compliance_report',
            'distribution' => 'reports.distribution_report',
            'fraud'        => 'reports.fraud_detection_report',
            'user'         => 'reports.user_activity_report',
            'qr'           => 'reports.qr_code_report',
        ];

        $view = $viewMap[$reportType] ?? 'reports.generic_report';

        $pdf = Pdf::loadView($view, [
            'data'         => $data,
            'filters'      => $filters,
            'report_type'  => $reportType,
            'generated_at' => now()->toDateTimeString(),
            'generated_by' => Auth::user()?->name ?? 'System',
        ])->setPaper('a4', 'landscape');

        return $pdf->download("{$filename}.pdf");
    }

    // ─────────────────────────────────────────────────────────────
    // exportToExcel
    // ─────────────────────────────────────────────────────────────

    public function exportToExcel(array $data, string $reportType, array $filters, string $filename): \Symfony\Component\HttpFoundation\Response
    {
        $sheets = $this->buildExcelSheets($data, $reportType, $filters);

        return Excel::download(
            new MultiSheetExport($sheets),
            "{$filename}.xlsx"
        );
    }

    // ─────────────────────────────────────────────────────────────
    // exportToCSV
    // ─────────────────────────────────────────────────────────────

    public function exportToCSV(array $data, string $reportType, string $filename): \Symfony\Component\HttpFoundation\Response
    {
        $csvData = $this->flattenForCsv($data, $reportType);

        $headers = [
            'Content-Type'        => 'text/csv; charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"{$filename}.csv\"",
        ];

        $callback = function () use ($csvData) {
            $handle = fopen('php://output', 'w');
            // BOM for Excel UTF-8 compatibility
            fwrite($handle, "\xEF\xBB\xBF");

            if (! empty($csvData)) {
                fputcsv($handle, array_keys($csvData[0]));
                foreach ($csvData as $row) {
                    fputcsv($handle, array_values($row));
                }
            }
            fclose($handle);
        };

        return response()->stream($callback, 200, $headers);
    }

    // ─────────────────────────────────────────────────────────────
    // Private Helpers
    // ─────────────────────────────────────────────────────────────

    private function buildExcelSheets(array $data, string $reportType, array $filters): array
    {
        $sheets = [];

        // Summary sheet
        $summaryRows = $this->buildSummaryRows($data, $reportType, $filters);
        $sheets[] = new SimpleSheet('Summary', ['Key', 'Value'], $summaryRows);

        // Detail sheet(s)
        $detail = $this->buildDetailRows($data, $reportType);
        if (! empty($detail['rows'])) {
            $sheets[] = new SimpleSheet($detail['title'], $detail['headings'], $detail['rows']);
        }

        return $sheets;
    }

    private function buildSummaryRows(array $data, string $reportType, array $filters): array
    {
        $rows = [
            ['Report Type',   ucfirst($reportType) . ' Report'],
            ['Generated At',  $data['generated_at'] ?? now()->toDateTimeString()],
            ['Generated By',  Auth::user()?->name ?? 'System'],
            ['Period From',   $filters['date_from'] ?? 'All time'],
            ['Period To',     $filters['date_to']   ?? 'Present'],
            ['Office Filter', $filters['office']    ?? 'All offices'],
            ['', ''],
        ];

        return match ($reportType) {
            'beneficiary' => array_merge($rows, [
                ['Total Beneficiaries',   $data['total'] ?? 0],
                ['Active',                $data['active'] ?? 0],
                ['Inactive',              $data['inactive'] ?? 0],
                ['Active %',              ($data['active_percentage'] ?? 0) . '%'],
                ['Newly Registered',      $data['newly_registered'] ?? 0],
                ['Avg Household Size',    $data['avg_household_size'] ?? 0],
                ['Avg Annual Income',     'PHP ' . number_format($data['avg_annual_income'] ?? 0, 2)],
            ]),
            'compliance' => array_merge($rows, [
                ['Total Beneficiaries',   $data['total'] ?? 0],
                ['Compliant',             $data['compliant_count'] ?? 0],
                ['Non-Compliant',         $data['non_compliant_count'] ?? 0],
                ['Partial',               $data['partial_count'] ?? 0],
                ['Overall Rate',          ($data['overall_rate'] ?? 0) . '%'],
                ['Education Rate',        ($data['education_rate'] ?? 0) . '%'],
                ['Health Rate',           ($data['health_rate'] ?? 0) . '%'],
                ['FDS Rate',              ($data['fds_rate'] ?? 0) . '%'],
            ]),
            'distribution' => array_merge($rows, [
                ['Total Amount',          'PHP ' . number_format($data['total_amount'] ?? 0, 2)],
                ['Distribution Count',    $data['total_count'] ?? 0],
                ['Average Payout',        'PHP ' . number_format($data['avg_payout'] ?? 0, 2)],
                ['Unique Beneficiaries',  $data['unique_beneficiaries'] ?? 0],
                ['Reconciled',            $data['reconciled'] ?? 0],
                ['Unreconciled',          $data['unreconciled'] ?? 0],
            ]),
            'fraud' => array_merge($rows, [
                ['Total Detections',      $data['total'] ?? 0],
                ['High Confidence',       $data['high_confidence'] ?? 0],
                ['Failed Verifications',  $data['failed_verifications'] ?? 0],
                ['Merged',                $data['action_breakdown']['merged'] ?? 0],
                ['Flagged',               $data['action_breakdown']['flagged'] ?? 0],
                ['Dismissed',             $data['action_breakdown']['dismissed'] ?? 0],
            ]),
            'user' => array_merge($rows, [
                ['Total Users Active',    count($data['per_user'] ?? [])],
                ['Inactive Users',        count($data['inactive_users'] ?? [])],
                ['Unusual Patterns',      count($data['unusual_patterns'] ?? [])],
            ]),
            'qr' => array_merge($rows, [
                ['Total QR Codes',        $data['total'] ?? 0],
                ['Active',                $data['active'] ?? 0],
                ['Expired',               $data['expired'] ?? 0],
                ['Invalid',               $data['invalid'] ?? 0],
                ['Regenerated',           $data['regenerated'] ?? 0],
                ['Replacement Rate',      ($data['replacement_rate'] ?? 0) . '%'],
                ['Avg Lifespan (days)',   $data['avg_lifespan_days'] ?? 0],
                ['Failed Scans',          $data['failed_scans'] ?? 0],
            ]),
            default => $rows,
        };
    }

    private function buildDetailRows(array $data, string $reportType): array
    {
        return match ($reportType) {
            'beneficiary' => [
                'title'    => 'By Municipality',
                'headings' => ['Municipality', 'Count'],
                'rows'     => collect($data['by_municipality'] ?? [])->map(fn ($r) => [$r['municipality'] ?? $r->municipality, $r['count'] ?? $r->count])->toArray(),
            ],
            'compliance' => [
                'title'    => 'Non-Compliant Beneficiaries',
                'headings' => ['Name', 'BIN', 'Municipality', 'Education %', 'Health %', 'FDS %', 'Status'],
                'rows'     => collect($data['non_compliant_list'] ?? [])->map(fn ($r) => [
                    $r['name'], $r['bin'], $r['municipality'],
                    $r['education_rate'], $r['health_rate'], $r['fds_rate'], $r['overall_status'],
                ])->toArray(),
            ],
            'distribution' => [
                'title'    => 'By Officer',
                'headings' => ['Name', 'Office', 'Count', 'Total Amount'],
                'rows'     => collect($data['by_officer'] ?? [])->map(fn ($r) => [
                    $r['name'], $r['office'], $r['count'], $r['total'],
                ])->toArray(),
            ],
            'fraud' => [
                'title'    => 'Fraud Events',
                'headings' => ['Type', 'Confidence', 'Primary Beneficiary', 'Duplicate Beneficiary', 'Action', 'Status', 'Detected At'],
                'rows'     => collect($data['events'] ?? [])->map(fn ($r) => [
                    $r['type'], $r['confidence'], $r['primary'], $r['duplicate'],
                    $r['action_taken'], $r['status'], $r['detected_at'],
                ])->toArray(),
            ],
            'user' => [
                'title'    => 'User Activity',
                'headings' => ['Name', 'Role', 'Office', 'Total Activities', 'Activities/Day'],
                'rows'     => collect($data['productivity'] ?? [])->map(fn ($r) => [
                    $r['name'], '', '', $r['total_activities'], $r['activities_per_day'],
                ])->toArray(),
            ],
            'qr' => [
                'title'    => 'Failed Scans by Beneficiary',
                'headings' => ['Beneficiary', 'BIN', 'Failure Count'],
                'rows'     => collect($data['failed_scans_by_beneficiary'] ?? [])->map(fn ($r) => [
                    $r['beneficiary'], $r['bin'], $r['failures'],
                ])->toArray(),
            ],
            default => ['title' => 'Details', 'headings' => [], 'rows' => []],
        };
    }

    private function flattenForCsv(array $data, string $reportType): array
    {
        return match ($reportType) {
            'beneficiary' => collect($data['by_municipality'] ?? [])->map(fn ($r) => [
                'Municipality' => $r['municipality'] ?? ($r->municipality ?? ''),
                'Count'        => $r['count'] ?? ($r->count ?? 0),
            ])->toArray(),
            'compliance' => collect($data['non_compliant_list'] ?? [])->map(fn ($r) => [
                'Name'           => $r['name'] ?? '',
                'BIN'            => $r['bin'] ?? '',
                'Municipality'   => $r['municipality'] ?? '',
                'Education Rate' => $r['education_rate'] ?? 0,
                'Health Rate'    => $r['health_rate'] ?? 0,
                'FDS Rate'       => $r['fds_rate'] ?? 0,
                'Status'         => $r['overall_status'] ?? '',
            ])->toArray(),
            'distribution' => collect($data['by_officer'] ?? [])->map(fn ($r) => [
                'Name'         => $r['name'] ?? '',
                'Office'       => $r['office'] ?? '',
                'Count'        => $r['count'] ?? 0,
                'Total Amount' => $r['total'] ?? 0,
            ])->toArray(),
            'fraud' => collect($data['events'] ?? [])->map(fn ($r) => [
                'Type'        => $r['type'] ?? '',
                'Confidence'  => $r['confidence'] ?? 0,
                'Primary'     => $r['primary'] ?? '',
                'Duplicate'   => $r['duplicate'] ?? '',
                'Action'      => $r['action_taken'] ?? '',
                'Status'      => $r['status'] ?? '',
                'Detected At' => $r['detected_at'] ?? '',
            ])->toArray(),
            'user' => collect($data['per_user'] ?? [])->map(fn ($r) => [
                'Name'             => $r['name'] ?? '',
                'Role'             => $r['role'] ?? '',
                'Office'           => $r['office'] ?? '',
                'Total Activities' => $r['total'] ?? 0,
            ])->toArray(),
            'qr' => collect($data['failed_scans_by_beneficiary'] ?? [])->map(fn ($r) => [
                'Beneficiary'   => $r['beneficiary'] ?? '',
                'BIN'           => $r['bin'] ?? '',
                'Failure Count' => $r['failures'] ?? 0,
            ])->toArray(),
            default => [],
        };
    }
}

// ─────────────────────────────────────────────────────────────
// Helper Classes for Maatwebsite Excel
// ─────────────────────────────────────────────────────────────

class SimpleSheet implements FromArray, WithHeadings, WithTitle, ShouldAutoSize, WithStyles
{
    public function __construct(
        private string $sheetTitle,
        private array  $headings,
        private array  $rows,
    ) {}

    public function array(): array    { return $this->rows; }
    public function headings(): array { return $this->headings; }
    public function title(): string   { return mb_substr($this->sheetTitle, 0, 31); }

    public function styles(Worksheet $sheet): array
    {
        return [
            1 => ['font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']], 'fill' => ['fillType' => 'solid', 'startColor' => ['rgb' => '1e40af']]],
        ];
    }
}

class MultiSheetExport implements \Maatwebsite\Excel\Concerns\WithMultipleSheets
{
    public function __construct(private array $sheets) {}

    public function sheets(): array { return $this->sheets; }
}
