<template>
  <div class="receipt-wrapper">
    <div class="receipt-actions">
      <button class="btn-print" @click="print">🖨️ Print</button>
      <a :href="downloadUrl" target="_blank" class="btn-download">📥 Download PDF</a>
    </div>

    <div class="receipt-card" ref="receiptRef">
      <!-- Header -->
      <div class="receipt-header">
        <div class="receipt-logo">🏛️</div>
        <div class="receipt-org">
          <div class="org-name">SECURE System</div>
          <div class="org-sub">Cash Grant Distribution Receipt</div>
        </div>
        <div class="receipt-num">{{ receiptNumber }}</div>
      </div>

      <!-- Amount highlight -->
      <div class="amount-highlight">
        <div class="ah-label">Amount Received</div>
        <div class="ah-amount">₱{{ formatAmount(distribution.payout_amount) }}</div>
        <div class="ah-period">For the period: <strong>{{ distribution.payout_period }}</strong></div>
      </div>

      <!-- Two column details -->
      <div class="details-grid">
        <div class="detail-col">
          <div class="section-heading">Beneficiary Information</div>
          <div class="detail-row">
            <span class="det-label">Name</span>
            <span class="det-val">{{ distribution.beneficiary?.family_head_name }}</span>
          </div>
          <div class="detail-row">
            <span class="det-label">BIN</span>
            <span class="det-val bin">{{ distribution.beneficiary?.bin }}</span>
          </div>
          <div class="detail-row">
            <span class="det-label">Barangay</span>
            <span class="det-val">{{ distribution.beneficiary?.barangay }}</span>
          </div>
          <div class="detail-row">
            <span class="det-label">Municipality</span>
            <span class="det-val">{{ distribution.beneficiary?.municipality }}</span>
          </div>
        </div>
        <div class="detail-col">
          <div class="section-heading">Distribution Details</div>
          <div class="detail-row">
            <span class="det-label">Date & Time</span>
            <span class="det-val">{{ formatDate(distribution.distributed_at) }}</span>
          </div>
          <div class="detail-row">
            <span class="det-label">Payment Method</span>
            <span class="det-val">
              <span class="method-badge" :class="methodClass(distribution.payment_method)">
                {{ methodLabel(distribution.payment_method) }}
              </span>
            </span>
          </div>
          <div class="detail-row">
            <span class="det-label">Reference No.</span>
            <span class="det-val ref">{{ distribution.transaction_reference_number }}</span>
          </div>
          <div class="detail-row">
            <span class="det-label">Distributed By</span>
            <span class="det-val">{{ distribution.distributed_by?.name }}</span>
          </div>
          <div class="detail-row" v-if="distribution.distributed_by?.office_location">
            <span class="det-label">Office</span>
            <span class="det-val">{{ distribution.distributed_by?.office_location }}</span>
          </div>
          <div class="detail-row" v-if="distribution.remarks">
            <span class="det-label">Remarks</span>
            <span class="det-val">{{ distribution.remarks }}</span>
          </div>
        </div>
      </div>

      <!-- Signature area (if available) -->
      <div class="signature-area">
        <div class="sig-box">
          <img v-if="distribution.signature_url" :src="distribution.signature_url" alt="Signature" class="sig-img" />
          <div v-else class="sig-placeholder"></div>
          <div class="sig-line"></div>
          <div class="sig-label">Beneficiary / Authorized Representative</div>
        </div>
        <div class="qr-box" v-if="distribution.id">
          <div class="qr-placeholder">
            <div class="qr-icon">QR</div>
          </div>
          <div class="qr-label">Scan to verify</div>
        </div>
      </div>

      <!-- Terms -->
      <div class="terms-box">
        <strong>Terms & Acknowledgment:</strong>
        By receiving this cash grant, the beneficiary acknowledges that the funds are intended for
        household welfare improvement in accordance with DSWD guidelines. Any discrepancy must be
        reported within 5 business days to the issuing office. This receipt serves as official proof
        of disbursement.
      </div>

      <!-- Footer -->
      <div class="receipt-footer">
        Generated by SECURE System · {{ formatDate(new Date().toISOString()) }}
        · For inquiries, contact your DSWD field office.
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  distribution: { type: Object, required: true },
})

const receiptNumber = computed(() => {
  const id = props.distribution?.id ?? 0
  return 'RCPT-' + String(id).padStart(8, '0')
})

const downloadUrl = computed(() =>
  props.distribution?.receipt_url ?? `/distribution/${props.distribution?.id}/receipt`
)

function formatDate (iso) {
  if (!iso) return '—'
  return new Date(iso).toLocaleDateString('en-PH', {
    year: 'numeric', month: 'long', day: '2-digit',
    hour: '2-digit', minute: '2-digit',
  })
}

function formatAmount (val) {
  return Number(val || 0).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

function methodLabel (m) {
  return { cash: 'Cash', 'e-wallet': 'E-Wallet', bank_transfer: 'Bank Transfer' }[m] ?? m
}

function methodClass (m) {
  return { cash: 'method-cash', 'e-wallet': 'method-ewallet', bank_transfer: 'method-bank' }[m] ?? ''
}

function print () { window.print() }
</script>

<style scoped>
.receipt-wrapper { display: flex; flex-direction: column; gap: 14px; }

.receipt-actions {
  display: flex;
  gap: 10px;
  justify-content: flex-end;
}

.btn-print, .btn-download {
  padding: 8px 18px;
  border-radius: 8px;
  font-weight: 700;
  font-size: 0.82rem;
  cursor: pointer;
  text-decoration: none;
  transition: all 0.15s;
}
.btn-print {
  background: #f1f5f9;
  border: 1px solid #e2e8f0;
  color: #475569;
}
.btn-print:hover { background: #e2e8f0; }
.btn-download {
  background: linear-gradient(135deg, #dc2626, #b91c1c);
  border: none;
  color: white;
}
.btn-download:hover { opacity: 0.88; transform: translateY(-1px); }

.receipt-card {
  background: white;
  border: 2px solid #e2e8f0;
  border-radius: 16px;
  overflow: hidden;
  font-family: 'Segoe UI', system-ui, sans-serif;
}

.receipt-header {
  display: flex;
  align-items: center;
  gap: 14px;
  padding: 18px 22px;
  background: linear-gradient(135deg, #1e40af, #1565c0);
  color: white;
}

.receipt-logo { font-size: 2rem; }
.org-name { font-size: 1.1rem; font-weight: 800; }
.org-sub  { font-size: 0.78rem; opacity: 0.8; }
.receipt-num { margin-left: auto; font-size: 0.78rem; font-family: monospace; opacity: 0.85; }

.amount-highlight {
  background: linear-gradient(135deg, #0f172a, #1e293b);
  color: white;
  text-align: center;
  padding: 22px 16px;
}
.ah-label  { font-size: 0.75rem; opacity: 0.7; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 4px; }
.ah-amount { font-size: 2.2rem; font-weight: 900; letter-spacing: -1px; }
.ah-period { font-size: 0.82rem; opacity: 0.8; margin-top: 6px; }

.details-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 0;
  padding: 20px 22px;
  border-bottom: 1px solid #f1f5f9;
}

.detail-col:first-child { padding-right: 20px; border-right: 1px solid #f1f5f9; }
.detail-col:last-child  { padding-left: 20px; }

.section-heading {
  font-size: 0.72rem;
  font-weight: 800;
  color: #1d4ed8;
  text-transform: uppercase;
  letter-spacing: 0.8px;
  margin-bottom: 12px;
  border-bottom: 1px solid #eff6ff;
  padding-bottom: 4px;
}

.detail-row {
  display: flex;
  gap: 8px;
  margin-bottom: 8px;
  font-size: 0.82rem;
  align-items: baseline;
}

.det-label {
  color: #94a3b8;
  min-width: 90px;
  flex-shrink: 0;
  font-size: 0.75rem;
}

.det-val { font-weight: 600; color: #1e293b; word-break: break-word; }
.det-val.bin { font-family: monospace; color: #1d4ed8; }
.det-val.ref { font-family: monospace; font-size: 0.7rem; color: #64748b; }

.method-badge {
  padding: 2px 8px;
  border-radius: 10px;
  font-size: 0.7rem;
  font-weight: 700;
}
.method-cash    { background: #f0fdf4; color: #15803d; }
.method-ewallet { background: #eff6ff; color: #1d4ed8; }
.method-bank    { background: #fff7ed; color: #c2410c; }

.signature-area {
  display: flex;
  align-items: flex-end;
  justify-content: space-between;
  padding: 18px 22px;
  border-bottom: 1px solid #f1f5f9;
}

.sig-box { display: flex; flex-direction: column; align-items: center; }
.sig-img  { max-height: 70px; max-width: 200px; margin-bottom: 4px; }
.sig-placeholder { height: 60px; width: 200px; }
.sig-line { width: 180px; border-top: 1px solid #334155; margin: 6px 0 4px; }
.sig-label { font-size: 0.72rem; color: #64748b; text-align: center; }

.qr-box { display: flex; flex-direction: column; align-items: center; }
.qr-placeholder {
  width: 80px; height: 80px;
  border: 2px solid #e2e8f0;
  border-radius: 6px;
  display: flex; align-items: center; justify-content: center;
  color: #cbd5e1;
  font-size: 0.75rem;
  font-family: monospace;
}
.qr-label { font-size: 0.68rem; color: #94a3b8; margin-top: 4px; }

.terms-box {
  padding: 14px 22px;
  font-size: 0.75rem;
  color: #64748b;
  background: #f8fafc;
  border-bottom: 1px solid #f1f5f9;
  line-height: 1.6;
}

.receipt-footer {
  padding: 10px 22px;
  font-size: 0.7rem;
  color: #94a3b8;
  text-align: center;
}

@media print {
  .receipt-actions { display: none; }
  .receipt-card { border: 1px solid #ccc; }
}
</style>
